### ISSUE TITLE
Allow STDIN as an input

### ISSUE THREAD

**Issue by tristanpemble** [yuloh/json-guard-cli#4]
Would be pretty cool to be able to pipe JSON output into the tool; if you provide `-` as the input filename it could use STDIN (I think that's a standard way to do it)

``` bash
curl https://api.mywebsite.com | json-guard validate - https://api.mywebsite.com/schema#
```

I may submit a PR if I have the time, but I thought I'd throw the idea out there

**Comment by yuloh** [comment]
That would be super handy 👍  I just had to `wget` something to check a github issue with this tool, would have been nice to pipe :)

**Comment by yuloh** [comment]
Closed by https://github.com/yuloh/json-guard-cli/commit/0d2a4c61a1fd725d550b8411e12de971af02fa3e
